export const employeeData = [
    {
      _id: 1,
      dni: '12345',
      fullname: 'Juan Pérez',
      workPosition: 'Desarrollador',
      area: 'Tecnología',
      immediateBoss: 'Ana Gómez',
      email: 'juan.perez@example.com',
      dateCompany: '2022-01-15',
      dateArea: '2022-02-20',
      birthdate: '1990-05-10',
      status: 'Activo',
    },
    {
      _id: 2,
      dni: '54321',
      fullname: 'María López',
      workPosition: 'Diseñador Gráfico',
      area: 'Diseño',
      immediateBoss: 'Carlos Rodríguez',
      email: 'maria.lopez@example.com',
      dateCompany: '2021-11-10',
      dateArea: '2021-12-15',
      birthdate: '1985-08-25',
      status: 'Inactivo',
    },
    {
      _id: 3,
      dni: '98765',
      fullname: 'Pedro García',
      workPosition: 'Gerente de Ventas',
      area: 'Ventas',
      immediateBoss: 'Laura Martínez',
      email: 'pedro.garcia@example.com',
      dateCompany: '2021-07-05',
      dateArea: '2022-01-10',
      birthdate: '1978-03-15',
      status: 'Activo',
    },
    {
      _id: 4,
      dni: '13579',
      fullname: 'Ana Gómez',
      workPosition: 'Recursos Humanos',
      area: 'RRHH',
      immediateBoss: 'David Sánchez',
      email: 'ana.gomez@example.com',
      dateCompany: '2021-09-20',
      dateArea: '2022-03-05',
      birthdate: '1989-11-30',
      status: 'Activo',
    },
  ];